version: '3.4'
services:
  app:
    container_name: misp-app
    image: misp
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - misp-db:/var/lib/mysql
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
      resources:
        limits:
          cpus: '2'
          memory: 500M
        reservations:
          cpus: '1'
          memory: 50M

volumes:
  misp-db:
    external: true