version: '2.2'
services:
  app:
    container_name: misp-app
    image: misp
    restart: unless-stopped
    networks: 
      - misp-frontend
    ports:
      - 80:80
      - 443:443
    volumes:
      - misp-db:/var/lib/mysql

volumes:
  misp-db:
    external: true
    
networks: 
  misp-frontend:
    driver: bridge